language: java
sudo: false # faster builds

jdk:
  - openjdk8

install:
  - curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar --output junit.jar --silent

script:
  - javac -d out src/fibo/*
  - javac -d out -cp out:junit.jar tests/fibo/*
  - java -jar junit.jar --class-path out --scan-class-path
